### ISSUE TITLE
I am encountering issue when loading model FaceNet.h5

### ISSUE THREAD

**Issue by praveenvattem** [shreyaspj20/Reliable-proctoring-AI#1]
The error is attached here for reference.Please check the reason for error.
![proctoring](https://user-images.githubusercontent.com/37047982/144761514-bbff9b11-2da3-4b67-9a99-5893054b61aa.png)

**Comment by shreyaspj20** [comment]
The facenet model seems to work fine. The error seems to be arising from facenet.py due to some variables being uninitialized.

**Comment by praveenvattem** [comment]
please update requirements.txt with this line of code to remove unstructured packages in the file :
pip list --format=freeze > requirements.txt

**Comment by shreyaspj20** [comment]
The requirements.txt file has been updated.
