### ISSUE TITLE
Error when loading FaceNet.h5 after running main.py

### ISSUE THREAD

**Issue by nht-1999** [shreyaspj20/Reliable-proctoring-AI#5]
![image](https://user-images.githubusercontent.com/56917422/171131941-7fcf2615-96c0-4d96-9570-67b30b3a6507.png)
I get this error when running main.py. How can I fix it? I used to search for this error on google and StackOverflow but had no result.

**Comment by saudhussainkhand** [comment]
I am getting the same error, any solution?
